services:
  - type: web
    name: jobhub-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
