services:
  - type: web
    name: jobhub-backend
    env: java
    rootDir: backend/JobHub
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/JobHub-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
